import colors from "./colors";

export const lightTheme = {
  BACKGROUND: colors.BACKGROUND,
  SURFACE: colors.SURFACE,
  TEXT_PRIMARY: colors.TEXT_PRIMARY,
  TEXT_SECONDARY: colors.TEXT_SECONDARY,
  TEXT_MUTED: colors.TEXT_MUTED,
  TEXT_INVERSE: colors.TEXT_INVERSE,
  TEXT_INVERSE_MUTED: colors.TEXT_INVERSE_MUTED,
  BORDER: colors.BORDER,

  PRIMARY: colors.PRIMARY,
  PRIMARY_DARK: colors.PRIMARY_DARK,
  PRIMARY_LIGHT: colors.PRIMARY_LIGHT,
  PRIMARY_LIGHT_TRANSPARENT: colors.PRIMARY_LIGHT_TRANSPARENT,

  ERROR: colors.ERROR,
  SUCCESS: colors.SUCCESS,
  WARNING: colors.WARNING,
};

export const darkTheme = {
  BACKGROUND: "#0F172A",
  SURFACE: "#1E293B",
  TEXT_PRIMARY: "#F8FAFC",
  TEXT_SECONDARY: "#CBD5E1",
  TEXT_MUTED: "#94A3B8",
  TEXT_INVERSE: "#1E293B",
  TEXT_INVERSE_MUTED: "#334155",
  BORDER: "#334155",

  PRIMARY: "#3B82F6",
  PRIMARY_DARK: colors.PRIMARY_DARK,
  PRIMARY_LIGHT: "#60A5FA",
  PRIMARY_LIGHT_TRANSPARENT: "#60A5FA20",

  ERROR: colors.ERROR,
  SUCCESS: colors.SUCCESS,
  WARNING: colors.WARNING,
};
